name: Matrix demo
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [22, 24]
                os: [ubuntu-latest, windows-latest]
                include:
                    - node-version: 18
                      os: ubuntu-latest
                exclude:
                    - node-version: 22
                      os: windows-latest
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build