name: test 02 starting project
on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: install dependencies
        working-directory: "02 Starting Project"
        run: npm ci

      - name: run lint
        working-directory: "02 Starting Project"
        run: npm run lint

      - name: Run test
        working-directory: "02 Starting Project"
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: install dependencies
        working-directory: "02 Starting Project"
        run: npm ci

      - name: Run build
        working-directory: "02 Starting Project"
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: |
            "02 Starting Project/dist"
            package.json

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Deploy
        run: echo "Deploying application"